"""add_shared_notes_table

Revision ID: 3312bb1aad82
Revises: 61facccc16d1
Create Date: 2025-11-28 00:30:28.930352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3312bb1aad82'
down_revision: Union[str, Sequence[str], None] = '61facccc16d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('encrypted_title', sa.Text(), nullable=True),
    sa.Column('encrypted_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id')
    )
    op.create_index('idx_shared_token_active', 'shared_notes', ['share_token', 'is_active'], unique=False)
    op.create_index(op.f('ix_shared_notes_id'), 'shared_notes', ['id'], unique=False)
    op.create_index(op.f('ix_shared_notes_share_token'), 'shared_notes', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_notes_share_token'), table_name='shared_notes')
    op.drop_index(op.f('ix_shared_notes_id'), table_name='shared_notes')
    op.drop_index('idx_shared_token_active', table_name='shared_notes')
    op.drop_table('shared_notes')
    # ### end Alembic commands ###
