"""add_folders_table

Revision ID: 34ae97d8ea36
Revises: 3312bb1aad82
Create Date: 2025-11-30 22:08:06.406867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34ae97d8ea36'
down_revision: Union[str, Sequence[str], None] = '3312bb1aad82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_name', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_folder_user_active', 'folders', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_folders_id'), 'folders', ['id'], unique=False)
    op.create_index(op.f('ix_folders_user_id'), 'folders', ['user_id'], unique=False)
    op.drop_index(op.f('idx_shared_token_active'), table_name='shared_notes')
    op.drop_index(op.f('ix_shared_notes_id'), table_name='shared_notes')
    op.drop_index(op.f('ix_shared_notes_share_token'), table_name='shared_notes')
    op.drop_table('shared_notes')
    op.add_column('notes', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_index('idx_note_folder', 'notes', ['folder_id'], unique=False)
    op.create_index(op.f('ix_notes_folder_id'), 'notes', ['folder_id'], unique=False)
    op.create_foreign_key(None, 'notes', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_index(op.f('ix_notes_folder_id'), table_name='notes')
    op.drop_index('idx_note_folder', table_name='notes')
    op.drop_column('notes', 'folder_id')
    op.create_table('shared_notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('share_token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('encrypted_title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('encrypted_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('shared_notes_note_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('shared_notes_pkey')),
    sa.UniqueConstraint('note_id', name=op.f('shared_notes_note_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_shared_notes_share_token'), 'shared_notes', ['share_token'], unique=True)
    op.create_index(op.f('ix_shared_notes_id'), 'shared_notes', ['id'], unique=False)
    op.create_index(op.f('idx_shared_token_active'), 'shared_notes', ['share_token', 'is_active'], unique=False)
    op.drop_index(op.f('ix_folders_user_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_id'), table_name='folders')
    op.drop_index('idx_folder_user_active', table_name='folders')
    op.drop_table('folders')
    # ### end Alembic commands ###
