"""Encrypt note title

Revision ID: 61facccc16d1
Revises: 48212c8b9f3d
Create Date: 2025-11-23 00:02:37.586279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61facccc16d1'
down_revision: Union[str, Sequence[str], None] = '48212c8b9f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('encrypted_title', sa.Text(), nullable=True))
    op.alter_column('notes', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='User ID who owns this note',
               existing_nullable=False)
    op.alter_column('notes', 'encrypted_content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='AES-256-GCM encrypted note content',
               existing_nullable=False)
    op.alter_column('notes', 'content_hash',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='SHA-256 hash for overwrite protection',
               existing_nullable=False)
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Note creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Last update timestamp',
               existing_nullable=True)
    op.alter_column('notes', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete flag',
               existing_nullable=False)
    op.drop_column('notes', 'title')
    op.alter_column('users', 'alias',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Username/alias (lowercase, alphanumeric + hyphens/underscores)',
               existing_nullable=False)
    op.alter_column('users', 'encrypted_alias',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Encrypted alias used to verify password correctness',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='User creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'last_accessed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Last access timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Soft delete flag',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete flag',
               existing_nullable=False)
    op.alter_column('users', 'last_accessed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Last access timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='User creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'encrypted_alias',
               existing_type=sa.TEXT(),
               comment='Encrypted alias used to verify password correctness',
               existing_nullable=False)
    op.alter_column('users', 'alias',
               existing_type=sa.VARCHAR(length=255),
               comment='Username/alias (lowercase, alphanumeric + hyphens/underscores)',
               existing_nullable=False)
    op.add_column('notes', sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Note title (can be encrypted or plain)'))
    op.alter_column('notes', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete flag',
               existing_nullable=False)
    op.alter_column('notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Last update timestamp',
               existing_nullable=True)
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Note creation timestamp',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notes', 'content_hash',
               existing_type=sa.VARCHAR(length=128),
               comment='SHA-256 hash for overwrite protection',
               existing_nullable=False)
    op.alter_column('notes', 'encrypted_content',
               existing_type=sa.TEXT(),
               comment='AES-256-GCM encrypted note content',
               existing_nullable=False)
    op.alter_column('notes', 'user_id',
               existing_type=sa.INTEGER(),
               comment='User ID who owns this note',
               existing_nullable=False)
    op.drop_column('notes', 'encrypted_title')
    # ### end Alembic commands ###
